#!/bin/bash

##
# run as root 
##

# disable kernel module
echo "stopping and unloading batman-adv kernel module"
rmmod batman-adv

#stop network manager to make the mesh network work
echo "starting Network Manager"
if [ -f /etc/debian_version ]; then
	service network-manager restart
elif [[ -f /etc/redhat-release ]] || [[ -f /etc/arch-release ]]; then
	NetworkManager
fi
